fix tests

diff --git a/docker/bin/setup b/docker/bin/setup
--- a/docker/bin/setup
+++ b/docker/bin/setup
@@ -11,19 +11,22 @@ touch $SETUP_LOG
 
 cat > /etc/postgresql/14/main/pg_hba.conf <<-EOF
 local  scram_db  postgres                  trust
-host   scram_db  postgres  127.0.0.1/32    trust
+host   scram_db  postgres    127.0.0.1/32  trust
 local  scram_db  scram_user                scram-sha-256
 host   scram_db  scram_user  127.0.0.1/32  scram-sha-256
 EOF
 
 cat >> /etc/postgresql/14/main/pg_hba.conf <<-EOF
-host   ldap_db   user1 127.0.0.1/32 trust
+host   ldap_db         user1                         127.0.0.1/32 trust
 host   auth_query_db   auth_query_user_scram_sha_256 127.0.0.1/32 trust
-host   auth_query_db   auth_query_user_md5 127.0.0.1/32 trust
-local  all       postgres                trust
-host   postgres  user1     127.0.0.1/32  trust
-host   all       postgres  127.0.0.1/32  trust
+host   auth_query_db   auth_query_user_md5           127.0.0.1/32 trust
+local  all             postgres                                   trust
+host   postgres        user1                         127.0.0.1/32 trust
+host   db1             user1                         127.0.0.1/32 trust
+host   all             postgres                      127.0.0.1/32 trust
 EOF
+
+sed -i 's/max_connections = 100/max_connections = 2000/g' /etc/postgresql/14/main/postgresql.conf
 
 # Start postgresql
 if ! /usr/bin/pg_ctlcluster 14 main start && psql -h localhost -p 5432 -U postgres  -c 'SELECT 1 AS ok'; then
@@ -33,7 +36,7 @@ if ! /usr/bin/pg_ctlcluster 14 main start && psql -h localhost -p 5432 -U postgr
 fi
 
 # Create databases
-for database_name in db scram_db ldap_db auth_query_db; do
+for database_name in db scram_db ldap_db auth_query_db db1; do
     sudo -u postgres createdb $database_name >> "$SETUP_LOG" 2>&1 || {
         echo "ERROR: 'createdb $database_name' failed, examine the log"
         cat "$SETUP_LOG"
@@ -75,3 +78,37 @@ psql -h localhost -p 5432 -U postgres -c "set password_encryption = 'scram-sha-2
     exit 1
 }
 
+# Create users
+psql -h localhost -p 5432 -U postgres -c "GRANT ALL ON DATABASE db1 TO user1" -d postgres >> $SETUP_LOG 2>&1 || {
+    echo "ERROR: users creation failed, examine the log"
+    cat "$SETUP_LOG"
+    cat "$PG_LOG"
+    exit 1
+}
+
+# Create users
+psql -h localhost -p 5432 -U postgres -c "alter user user1 with connection limit 1000" -d postgres >> $SETUP_LOG 2>&1 || {
+    echo "ERROR: users creation failed, examine the log"
+    cat "$SETUP_LOG"
+    cat "$PG_LOG"
+    exit 1
+}
+
+# Create users
+psql -h localhost -p 5432 -U user1 -d db1 -c "CREATE SCHEMA sh1" >> $SETUP_LOG 2>&1 || {
+	echo "ERROR: users creation failed, examine the log"
+	cat "$SETUP_LOG"
+	cat "$PG_LOG"
+	exit 1
+}
+
+for i in `seq 0 9`
+do
+	# Create users
+	psql -h localhost -p 5432 -U user1 -d db1 -c "CREATE TABLE sh1.foo$i (i int)" >> $SETUP_LOG 2>&1 || {
+		echo "ERROR: users creation failed, examine the log"
+		cat "$SETUP_LOG"
+		cat "$PG_LOG"
+		exit 1
+	}
+done
