Add auth query basic tests & add test with restart for lag polling (#387)
* Add auth query basic tests

* Remove unused file ini.sql

* Refactor lag polling tests

diff --git a/docker/bin/setup b/docker/bin/setup
--- a/docker/bin/setup
+++ b/docker/bin/setup
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -ex
+
 service postgresql stop || true
 
 export PG_LOG=/var/log/postgresql/postgresql-14-main.log
@@ -12,10 +14,12 @@ local  scram_db  postgres                  trust
 host   scram_db  postgres  127.0.0.1/32    trust
 local  scram_db  scram_user                scram-sha-256
 host   scram_db  scram_user  127.0.0.1/32  scram-sha-256
-host   ldap_db   user1 127.0.0.1/32 trust
 EOF
 
 cat >> /etc/postgresql/14/main/pg_hba.conf <<-EOF
+host   ldap_db   user1 127.0.0.1/32 trust
+host   auth_query_db   auth_query_user_scram_sha_256 127.0.0.1/32 trust
+host   auth_query_db   auth_query_user_md5 127.0.0.1/32 trust
 local  all       postgres                trust
 host   postgres  user1     127.0.0.1/32  trust
 host   all       postgres  127.0.0.1/32  trust
@@ -29,7 +33,7 @@ if ! /usr/bin/pg_ctlcluster 14 main start && psql -h localhost -p 5432 -U postgr
 fi
 
 # Create databases
-for database_name in db scram_db ldap_db; do
+for database_name in db scram_db ldap_db auth_query_db; do
     sudo -u postgres createdb $database_name >> "$SETUP_LOG" 2>&1 || {
         echo "ERROR: 'createdb $database_name' failed, examine the log"
         cat "$SETUP_LOG"
@@ -48,6 +52,23 @@ psql -h localhost -p 5432 -U postgres -c "set password_encryption = 'scram-sha-2
 
 # Create users
 psql -h localhost -p 5432 -U postgres -c "create role user1 with login" -d ldap_db >> $SETUP_LOG 2>&1 || {
+    echo "ERROR: users creation failed, examine the log"
+    cat "$SETUP_LOG"
+    cat "$PG_LOG"
+    exit 1
+}
+
+# Create users
+psql -h localhost -p 5432 -U postgres -c "set password_encryption TO 'md5'; create user auth_query_user_md5 with password 'passwd'" -d postgres >> $SETUP_LOG 2>&1 || {
+    echo "ERROR: users creation failed, examine the log"
+    cat "$SETUP_LOG"
+    cat "$PG_LOG"
+    exit 1
+}
+
+
+# Create users
+psql -h localhost -p 5432 -U postgres -c "set password_encryption = 'scram-sha-256'; create user auth_query_user_scram_sha_256 with password 'passwd'" -d postgres >> $SETUP_LOG 2>&1 || {
     echo "ERROR: users creation failed, examine the log"
     cat "$SETUP_LOG"
     cat "$PG_LOG"
