LDAP auth in od

diff --git a/docker/bin/setup b/docker/bin/setup
--- a/docker/bin/setup
+++ b/docker/bin/setup
@@ -3,24 +3,27 @@
 export SETUP_LOG=/var/log/postgresql/postgresql-13-main.log
 
 cat > /etc/postgresql/13/main/pg_hba.conf <<-EOF
-local  scram_db  all                scram-sha-256
-host   scram_db  all  127.0.0.1/32  scram-sha-256
+local  scram_db  postgres                  trust
+host   scram_db  postgres  127.0.0.1/32    trust
+local  scram_db  scram_user                scram-sha-256
+host   scram_db  scram_user  127.0.0.1/32  scram-sha-256
+host   ldap_db   user1 127.0.0.1/32 trust
 EOF
 
 cat >> /etc/postgresql/13/main/pg_hba.conf <<-EOF
-local  all       all                trust
-host   all       all  127.0.0.1/32  trust
+local  all       postgres                trust
+host   all       postgres  127.0.0.1/32  trust
 EOF
 
 # Start postgresql
-if ! /usr/bin/pg_ctlcluster 13 main start && psql -h localhost -p 5432 -U postgres -c 'SELECT 1 AS ok'; then
+if ! /usr/bin/pg_ctlcluster 13 main start && psql -h localhost -p 5432 -U postgres  -c 'SELECT 1 AS ok'; then
     echo "ERROR: 'pg_ctl start' failed, examine the log"
     cat "$SETUP_LOG"
     exit 1
 fi
 
 # Create databases
-for database_name in db scram_db; do
+for database_name in db scram_db ldap_db; do
     sudo -u postgres createdb $database_name >> "$SETUP_LOG" 2>&1 || {
         echo "ERROR: 'createdb $database_name' failed, examine the log"
         cat "$SETUP_LOG"
@@ -29,7 +32,14 @@ for database_name in db scram_db; do
 done
 
 # Create users
-psql -h localhost -p 5432 -U postgres  -c "set password_encryption = 'scram-sha-256'; create user scram_user password 'scram_user_password';" db >> $SETUP_LOG 2>&1 || {
+psql -h localhost -p 5432 -U postgres -c "set password_encryption = 'scram-sha-256'; create user scram_user password 'scram_user_password';" -d scram_db >> $SETUP_LOG 2>&1 || {
+    echo "ERROR: users creation failed, examine the log"
+    cat "$SETUP_LOG"
+    exit 1
+}
+
+# Create users
+psql -h localhost -p 5432 -U postgres -c "create role user1 with login" -d ldap_db >> $SETUP_LOG 2>&1 || {
     echo "ERROR: users creation failed, examine the log"
     cat "$SETUP_LOG"
     exit 1
