Gorm tests (#594)
* its work

* refactoring

* refactoring

* add test.sh

* refactoring, change docker-compose-test

* add logs

* fix?

* add gorm-test local

* fix

* refactoring

* add copy test

* refactoring

* fix test

* fix entrypoint

* rebase master

* its work

* refactoring

* refactoring

* add test.sh

* refactoring, change docker-compose-test

* add logs

* fix?

* add gorm-test local

* fix

* refactoring

* fix

diff --git a/docker/bin/setup b/docker/bin/setup
--- a/docker/bin/setup
+++ b/docker/bin/setup
@@ -135,6 +135,22 @@ psql -h localhost -p 5432 -U postgres  -c "create user user_addr_correct passwor
   exit 1
 }
 
+# Create users
+psql -h localhost -p 5432 -U postgres -c "create role xproto SUPERUSER LOGIN" -d xproto_db >> $SETUP_LOG 2>&1 || {
+    echo "ERROR: users creation failed, examine the log"
+    cat "$SETUP_LOG"
+    cat "$PG_LOG"
+    exit 1
+}
+
+# Create users
+psql -h localhost -p 5432 -U postgres  -c "create user \"spqr-console\";" >> $SETUP_LOG 2>&1 || {
+  echo "ERROR: users creation failed, examine the log"
+  cat "$SETUP_LOG"
+  cat "$PG_LOG"
+  exit 1
+}
+
 for i in `seq 0 9`
 do
 	# Create tables
@@ -165,20 +181,6 @@ psql -h localhost -p 5432 -U postgres -c "create user ldap_readonly with passwor
 }
 
 psql -h localhost -p 5432 -U postgres -c "set password_encryption TO 'md5'; create user ldap_rw with password 'ldap_pass_rw'" -d ldap_db2 >> $SETUP_LOG 2>&1 || {
-    echo "ERROR: users creation failed, examine the log"
-    cat "$SETUP_LOG"
-    cat "$PG_LOG"
-    exit 1
-}
-
-psql -h localhost -p 5432 -U postgres -c "create role xproto SUPERUSER LOGIN" -d xproto_db >> $SETUP_LOG 2>&1 || {
-    echo "ERROR: users creation failed, examine the log"
-    cat "$SETUP_LOG"
-    cat "$PG_LOG"
-    exit 1
-}
-
-psql -h localhost -p 5432 -U postgres -c "create user \"spqr-console\"" -d "spqr-console" >> $SETUP_LOG 2>&1 || {
     echo "ERROR: users creation failed, examine the log"
     cat "$SETUP_LOG"
     cat "$PG_LOG"
